language: python
python:
- '2.6'
- '2.7'
install:
- pip install six
- pip install python-coveralls
script: nosetests
after_success:
- coveralls
deploy:
  provider: pypi
  user: plasmashadow
  password:
    secure: HNpE0UJxvPp/GyH0UVMvCS3UGIYiviT3fkNxGVIP74XJZlvfg2qFTdnYYR8Blf04XzGDS8e6REBayRVNmVYN3UXaa5GmBQBGGwcZh6CTvKSdbWlug4OuDoO3tgTTcB38rRHkjWqYwjgVJwJ/OBTcQw1N8BynTBaLYDF958VJUc9JF+L4v2QFJFmzDmg4RIUMkMJ5qmcNRuGr4Xjp0OQ96D6dsYUITUy5lyxrf8VO9LEDOrcQGTh5BDzWWtwYTIQ5MKzZySSkab/H9px4UuQJRlPLTrwaJiz7gaNKapSEX1IntejBjoNNgz+Oi474uMgv4EkJbqQIU4TjDkt2j9iCFODy8JTM0nEI2ZgrCmbwVV+facrdyWe1uQ7FqTqAeZCicr6ZsYpnPAY+b85jRa2Rn0N9Ej19wxT+R2eb/bGgbnmrpBYFLPIFa7N0Ywx7rjHKYaKESYdbKG1ytuTI+0jQLVkA78M5Wq9BhosryOTlO6OKgLiRNoi3iBsiIykM/GOZckELBmCcd8e/fpRwDMf72tXH+4upSbWXbJUdgeQnz/uUnn/j6i9eFcjC82Hwno/KYD2Q0arc45ub5Z6IyD7fsNpEAihzIBbqVPmQeSDMxWdh3FnPVwI48rZemy3OfF2ZHpZfxpLClwkYhE6GgiM5KlW71JAjgSgKaji/svB6Ggc=
  on:
    repo: plasmashadow/pyhttp
    branch: master
